-- CreateEnum
CREATE TYPE "PapelSignatarioPadrao" AS ENUM ('ASSINAR', 'APROVAR', 'RECONHECER', 'ASSINAR_COMO_PARTE', 'ASSINAR_COMO_TESTEMUNHA', 'ASSINAR_COMO_INTERVENIENTE', 'ACUSAR_RECEBIMENTO', 'ASSINAR_COMO_EMISSOR_ENDOSSANTE_AVALISTA', 'ASSINAR_COMO_EMISSOR_ENDOSSANTE_AVALISTA_FIADOR', 'ASSINAR_COMO_FIADOR', 'ASSINAR_COMO_PARTE_E_FIADOR', 'ASSINAR_COMO_RESPONSAVEL_SOLIDARIO', 'ASSINAR_COMO_PARTE_E_RESPONSAVEL_SOLIDARIO');

-- AlterTable
ALTER TABLE "signatarios_padrao" ADD COLUMN     "estagio" INTEGER NOT NULL,
ADD COLUMN     "papel" "PapelSignatarioPadrao" NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "signatarios_padrao_email_key" ON "signatarios_padrao"("email");
